### ISSUE TITLE
Runtime error in production mode

### ISSUE THREAD

**Issue by gschuager** [manfredsteyer/mf-angular-13#2]
When trying to run the application in production mode, the following error shows in the browser console:
```
polyfills.js:1 Uncaught Error: Automatic publicPath is not supported in this browser
    at polyfills.js:1
    at polyfills.js:1
```

![image](https://user-images.githubusercontent.com/139658/144902160-90904915-7332-4edb-b860-a66ba82c87a4.png)

To run the app I updated package.json with the following changes:

```diff
-    "@angular-architects/module-federation": "14.0.0-beta.5",
-    "@angular-architects/module-federation-tools": "14.0.0-beta.3",
+    "@angular-architects/module-federation": "14.0.0-beta.0",
+    "@angular-architects/module-federation-tools": "14.0.0-beta.0",
```

Then removed package-lock.json, install dependencies with `npm -i --legacy-peer-deps` and executed:

```
ng serve shell --configuration=production
ng serve mfe1 --configuration=production
```

**Comment by gobedson** [comment]
hello @gschuager  was you able to solve this ?

**Comment by gschuager** [comment]
I didn't try anymore with this repo.

The underlying issue was solved; see https://github.com/angular-architects/module-federation-plugin/issues/96
